# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HBONOW' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HBONOW

pod 'FirebaseCore'
pod 'FirebaseFirestore'
pod 'Firebase/ABTesting'
pod 'Firebase/Functions'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Firebase/Core'

end












